2021-12-15 12:52:43,435 ERROR: Exception on / [GET] [in /home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ebanks/workspace/microblog/app/routes.py", line 32, in index
    return render_template('index.html', title="Home", form=form, posts=posts)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ebanks/workspace/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ebanks/workspace/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ebanks/workspace/microblog/app/templates/index.html", line 19, in block 'content'
    {% include "_post.html" %}
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ebanks/workspace/microblog/app/templates/_post.html", line 7, in template
    <a href="{{ url_for('user, username=post.author.username) }}">
jinja2.exceptions.TemplateSyntaxError: unexpected char "'" at 184
2021-12-15 12:52:47,518 ERROR: Exception on / [GET] [in /home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ebanks/workspace/microblog/app/routes.py", line 32, in index
    return render_template('index.html', title="Home", form=form, posts=posts)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ebanks/workspace/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ebanks/workspace/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ebanks/workspace/microblog/app/templates/index.html", line 19, in block 'content'
    {% include "_post.html" %}
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ebanks/workspace/microblog/app/templates/_post.html", line 7, in template
    <a href="{{ url_for('user, username=post.author.username) }}">
jinja2.exceptions.TemplateSyntaxError: unexpected char "'" at 184
2021-12-15 12:52:50,447 ERROR: Exception on /explore [GET] [in /home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ebanks/workspace/microblog/app/routes.py", line 39, in explore
    return render_template('index.html', title="Explore", posts=posts)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ebanks/workspace/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/ebanks/workspace/microblog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ebanks/workspace/microblog/app/templates/index.html", line 19, in block 'content'
    {% include "_post.html" %}
  File "/home/ebanks/workspace/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ebanks/workspace/microblog/app/templates/_post.html", line 7, in template
    <a href="{{ url_for('user, username=post.author.username) }}">
jinja2.exceptions.TemplateSyntaxError: unexpected char "'" at 184
